name: Pytest & flake8 control push
on: push
job:
  qa:
    name: Check Tests
    runs-on: ubuntu-24.04
steps:
  - name: Checkout respository
    uses: actions/checkout@v4

  - name: setup python
    uses: actions/setup-python@v5
    with:
      python-version: "3.x"

  - name: Install pytest and flake8
    run: |
      pip install pytest
      pip install flake8

  - name: Run tests
    run: |
      pytest


  - name: Run flake8
    uses: py-actions/flake8@v2
